### PR TITLE
add listBook and listReview

### PR DESCRIPTION
**Pull request by EleenYang**

### CODE REVIEW

**Comment by r4venz** [comment]
why can you list review while there is no review in the model???

**Review by 0blivious — COMMENTED** [review]
Can you try to combine the listBook and findBook command according to the previous UG. That is listBook support search by book name directly

**Review by 0blivious — COMMENTED** [review]
And pls write all relevant test also

**Comment by joey-jiang6** [comment]
well down! and remember always pr new code with relevant tests.

**Pull request merged**
